AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.9
  Recipe Crate
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 900
    MemorySize: 256

Parameters:
  #This should be copy pasted to all the SAM App you are making 
  Environment:
    Type: String
    Default: prod
    AllowedValues:
      - test
      - prod

Resources:
  RecipeCrateFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      FunctionName: !Sub ${Environment}-recipe-crate-function
      Policies:
      # Allow read access to secret manager
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:prod/recipe-crate/openai-key-L204ig
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerTag: python3.10-v1